version: '3'

services:
  node:
    image: magida/iot-uplink
    restart: always
    ports:
      - "80:3000"
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Passw0rd
  volumes:
    - data:/var/lib/postgresql

volumes:
  data

networks:
  default:
    driver: bridge